# Generated by Django 4.2.4 on 2023-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancing_pony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='dishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
