# Generated by Django 4.2.4 on 2023-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancing_pony', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
