# Generated by Django 4.2.4 on 2023-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancing_pony', '0003_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ratings',
            field=models.JSONField(default=list),
        ),
    ]
